### ISSUE TITLE
Question regarding NA assignments

### ISSUE THREAD

**Issue by shimon166** [mhahsler/streamMOA#3]
First of all I would like to thank you for the great StreamMOA R package.
There is something I did not understand from the documentation of the package and would love to sharpen the knowledge.
get_assignment function of any stream algorithm return assignments to each given point or NA if any cluster does not fit unless model and type parameters is 'auto' and than if the model does not fit to any cluster "nn" method will assign its decision.

Below is a quote from the documentation:
״method = "auto" selects model-based assignment if available and otherwise defaults to nearest neighbor assignment. Note that model-based assignment might result in some points not being assigned to any cluster (i.e., an assignment value of NA) which indicates a noise data point.״

If I understand correctly, when I enter model = auto I should not get NA in the results but in fact I do get NA.
 assignments <- get_assignment(dStream,points[,0:5],type = "auto",method="auto")
Could you please refine my reason for receiving NAs in this case?

**Comment by mhahsler** [comment]
This is a misunderstanding due to my sloppy writing of the manual page. auto does not mix model-based assignment an nn to avoid NAs. If the model-based assignment is available then it is used exclusively and will return NAs. auto is just there for convenience to always get some kind of assignment.

**Comment by mhahsler** [comment]
I will update the manual page to make this clearer.
